#!/bin/bash

# Object Storage Upload Script with Hardcoded Credentials
# Samsung Cloud Platform v2 - Object Storage Integration
# Generated by variables_manager.ps1 on 2025-10-12 19:29:34
# 스크립트를 홈 디렉토리(/home/rocky/)에서 실행
cd /home/rocky/

echo "========================================="
echo "Object Storage Upload Script"
echo "Samsung Cloud Platform v2"
echo "========================================="

# 색상 함수
red() { echo -e "\033[31m$1\033[0m"; }
green() { echo -e "\033[32m$1\033[0m"; }
yellow() { echo -e "\033[33m$1\033[0m"; }
cyan() { echo -e "\033[36m$1\033[0m"; }

# 로깅 함수
log_info() { echo "[INFO] $1"; }
log_success() { echo "$(green "[SUCCESS]") $1"; }
log_error() { echo "$(red "[ERROR]") $1"; }
log_warning() { echo "$(yellow "[WARNING]") $1"; }

# Hardcoded Object Storage credentials
ACCESS_KEY="put_your_authentificate_access_key_here"
SECRET_KEY="put_your_authentificate_secret_key_here"
BUCKET_STRING="put_your_account_id_here"

# Object Storage 엔드포인트 설정 (README.md 참조)
ENDPOINT_URL="https://object-store.private.kr-west1.e.samsungsdscloud.com"
BUCKET_NAME="ceweb"
REGION="kr-west1"

log_success "Object Storage configuration loaded (hardcoded):"
echo "  Access Key: ${ACCESS_KEY:0:8}..."
echo "  Bucket String: $BUCKET_STRING"
echo "  Endpoint: $ENDPOINT_URL"
echo "  Bucket Name: $BUCKET_NAME"

# AWS CLI 설치 확인 및 설치 (README.md 참조)
log_info "Checking AWS CLI installation..."

if command -v aws &> /dev/null; then
    AWS_VERSION=$(aws --version 2>&1 | cut -d' ' -f1 | cut -d'/' -f2)
    log_info "AWS CLI is already installed (version: $AWS_VERSION)"

    # 버전 2.x인지 확인
    if [[ "$AWS_VERSION" < "2.0" ]]; then
        log_warning "AWS CLI version 1.x detected, upgrading to version 2..."
        INSTALL_AWSCLI=true
    else
        log_success "AWS CLI version 2.x is already installed"
        INSTALL_AWSCLI=false
    fi
else
    log_info "AWS CLI not found, installing AWS CLI v2..."
    INSTALL_AWSCLI=true
fi

if [ "$INSTALL_AWSCLI" = true ]; then
    # README.md에 따른 AWS CLI 설치 과정
    log_info "Installing AWS CLI following README.md instructions..."

    # 기존 설치 삭제
    sudo yum remove -y awscli 2>/dev/null || true

    # Object Storage를 위한 AWS CLI 설치
    sudo dnf install -y unzip
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install

    # 정리
    rm -rf aws awscliv2.zip

    log_success "AWS CLI v2 installed successfully"
fi

# AWS CLI 환경 구성 (README.md 참조)
log_info "Configuring AWS CLI for Object Storage..."

# AWS credentials 파일 생성
cd /home/rocky/
mkdir -p ~/.aws

cat > ~/.aws/credentials << EOF
[default]
aws_access_key_id = $ACCESS_KEY
aws_secret_access_key = $SECRET_KEY
EOF

cat > ~/.aws/config << EOF
[default]
region = $REGION
EOF

chmod 600 ~/.aws/credentials ~/.aws/config

log_success "AWS CLI configured successfully"

# 연결 테스트
log_info "Testing Object Storage connection..."
if aws s3 ls s3://$BUCKET_NAME --endpoint-url $ENDPOINT_URL >/dev/null 2>&1; then
    log_success "Object Storage connection successful"
else
    log_warning "Object Storage connection test failed, but proceeding..."
    log_info "This may be normal if the bucket doesn't exist yet"
fi

# 미디어 디렉토리 확인
MEDIA_DIR="./ceweb/media"
if [ ! -d "$MEDIA_DIR" ]; then
    log_error "Media directory not found: $MEDIA_DIR"
    log_error "Please ensure the web application is properly deployed"
    exit 1
fi

# 미디어 파일 현황 확인
log_info "Checking media directory contents..."
TOTAL_FILES=$(find "$MEDIA_DIR" -type f | wc -l)
TOTAL_SIZE=$(du -sh "$MEDIA_DIR" 2>/dev/null | cut -f1)

if [ "$TOTAL_FILES" -eq 0 ]; then
    log_warning "No files found in $MEDIA_DIR"
    echo "Nothing to upload."
    exit 0
fi

log_info "Found $TOTAL_FILES files ($TOTAL_SIZE) in $MEDIA_DIR"

# 사용자 확인 (기본값 Y)
echo ""
yellow "========================================="
yellow "UPLOAD CONFIRMATION"
yellow "========================================="
echo ""
echo "The following will be uploaded to Object Storage:"
echo "  Source: $MEDIA_DIR"
echo "  Destination: s3://$BUCKET_NAME/media"
echo "  Endpoint: $ENDPOINT_URL"
echo "  Files: $TOTAL_FILES files ($TOTAL_SIZE)"
echo ""

# 기본값이 Y인 확인
read -p "$(yellow "Do you want to proceed with the upload? [Y/n]: ")" -n 1 -r
echo

# 기본값 처리 (엔터만 누른 경우 Y로 처리)
if [[ -z "$REPLY" ]]; then
    REPLY="Y"
fi

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log_info "Upload cancelled by user"
    exit 0
fi

# Object Storage로 업로드 (README.md의 명령 참조)
log_info "Starting upload to Object Storage..."
echo ""

# README.md 명령: aws s3 cp media s3://{버킷명}/media --recursive --endpoint-url [Private Endpoint명]
cd /home/rocky/ceweb

log_info "Executing: aws s3 cp media s3://$BUCKET_NAME/media --recursive --endpoint-url $ENDPOINT_URL"

aws s3 cp media "s3://$BUCKET_NAME/media" --recursive --endpoint-url "$ENDPOINT_URL"

UPLOAD_RESULT=$?

if [ $UPLOAD_RESULT -eq 0 ]; then
    log_success "Upload completed successfully!"
    echo ""

    # 업로드 확인
    log_info "Verifying upload..."
    UPLOADED_FILES=$(aws s3 ls "s3://$BUCKET_NAME/media" --recursive --endpoint-url "$ENDPOINT_URL" | wc -l)
    log_success "Verified: $UPLOADED_FILES files uploaded"

    # Public URL 정보 제공 (README.md 참조)
    echo ""
    cyan "========================================="
    cyan "OBJECT STORAGE INFORMATION"
    cyan "========================================="
    echo ""
    echo "$(green "Files successfully uploaded to Object Storage")"
    echo ""
    echo "Public URL structure:"
    echo "  https://object-store.kr-west1.e.samsungsdscloud.com/$BUCKET_STRING:$BUCKET_NAME/media/[filename]"
    echo ""
    echo "Private URL structure:"
    echo "  $ENDPOINT_URL/$BUCKET_STRING:$BUCKET_NAME/media/[filename]"
    echo ""
    echo "Web application configuration:"
    echo "  Update your web application to use the Object Storage URLs"
    echo "  for serving static media files."
    echo ""

    # README.md에 언급된 애플리케이션 전환 방법 안내
    echo "$(cyan "Next steps (from README.md):")"
    echo "  1. Update web server paths from './media' to Object Storage URLs"
    echo "  2. Consider switching application files:"
    echo "     mv index.html index_bk.html"
    echo "     mv index_obj.html index.html"
    echo ""
else
    log_error "Upload failed with exit code $UPLOAD_RESULT"
    log_error "Please check your Object Storage configuration and network connectivity"
    exit 1
fi

echo ""
log_success "Object Storage upload script completed successfully!"
echo "========================================="
